###
POST http://localhost:7000/user/users HTTP/1.1
Content-Type: application/json

{
    "name":"lao",
    "lastname":"romero",
    "phone":"2",
    "email":"joser@gmail.com",
    "cp":"9500",
    "CiudadLocalidad":"zongolica",
    "referencia":"frente a cfe"
    
}
###
GET http://localhost:7000/api/users HTTP/1.1
###
GET http://localhost:7000/api/users/63d49dd344c1aa2176504405  HTTP/1.1
###
PUT http://localhost:7000/api/users/63d49dd344c1aa2176504405 HTTP/1.1
Content-Type: application/json

{
    "name":"Lidia",
    "lastname":"ortega",
    "phone":"2717064016",
    "email":"lidia99@gmail.com",
    "cp":"9500",
    "CiudadLocalidad":"zongolica",
    "referecia":"frente a cfe"
    
}
###
DELETE http://localhost:7000/api/users/63d49dd344c1aa2176504405 HTTP/1.1